#!/bin/sh

input="$1"
shift
bgcolor="$1"
shift
dvipngargs="$*"

latex=latex
dvipng=dvipng
origpwd=`pwd`
stderr=`mktemp`

# imagemagick
convert=convert
convertargs="-trim -transparent $bgcolor"

latexargs="-interaction=nonstopmode"

trap cleanup 2 3 9 10 11 15

cleanup() {
  echo "INPUT:"
  cat $input
  echo "STDERR:"
  cat $stderr
  test -f $stderr && rm $stderr
}

test -z $input && {
  echo ERROR: need input >&2
  cleanup
  exit 1
}

$latex $latexargs $input >$stderr 2>&1 || {
  echo "ERROR: problems during latex"
  cleanup
  exit 1
}

$dvipng $dvipngargs $input.dvi >$stderr 2>&1  || {
  echo "ERROR: converting dvi to image"
  echo "       using $dvipng $dvipngargs $input.dvi"
  cleanup
  exit 1
}

for img in *.png; do
  $convert $convertargs $img $img >$stderr 2>&1 || {
    echo "ERROR: problems converting $img"
    cleanup
    exit 1
  }
done

cleanup
